name: GIFD2
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - blas
  - brotlipy
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - cryptography
  - cudatoolkit
  - ffmpeg
  - freetype
  - giflib
  - gmp
  - gnutls
  - idna
  - intel-openmp
  - jpeg
  - lame
  - lcms2
  - ld_impl_linux-64
  - libffi
  - libgcc-ng
  - libiconv
  - libidn2
  - libpng
  - libstdcxx-ng
  - libtasn1
  - libtiff
  - libunistring
  - libwebp
  - libwebp-base
  - lz4-c
  - mkl
  - ncurses
  - nettle
  - numpy=1
  - openh264
  - openssl
  - pillow
  - pip
  - pycparser
  - pyopenssl
  - pysocks
  - pytorch
  - pytorch-cuda=11.8
  - pytorch-mutex
  - torchaudio
  - torchvision
  - readline
  - requests
  - setuptools
  - six
  - sqlite
  - tk
  - typing_extensions
  - urllib3
  - wheel
  - xz
  - zlib
  - zstd
  - pip:
    - absl-py
    - antlr4-python3-runtime
    - argon2-cffi
    - argon2-cffi-bindings
    - asttokens
    - attrs
    - backcall
    - bayesian-optimization
    - beautifulsoup4
    - bleach
    - boto3
    - botocore
    - cachetools
    - cma
    - cycler
    - debugpy
    - decorator
    - defusedxml
    - entrypoints
    - executing
    - fastjsonschema
    - fonttools
    - google-auth
    - google-auth-oauthlib
    - gpytorch
    - grpcio
    - hydra
    - hydra-core
    - imageio
    - importlib-metadata
    - importlib-resources
    - ipykernel
    - ipython
    - ipython-genutils
    - ipywidgets
    - jedi
    - jinja2
    - jmespath
    - joblib
    - jsonschema
    - jupyter
    - kiwisolver
    - lpips
    - markdown
    - markupsafe
    - matplotlib
    - matplotlib-inline
    - mistune
    - nbclient
    - nbconvert
    - nbformat
    - nest-asyncio
    - networkx
    - nevergrad
    - ninja
    - notebook
    - oauthlib
    - omegaconf
    - opencv-python
    - packaging
    - pandas==1.*
    - pandocfilters
    - parso
    - pexpect
    - pickleshare
    - prometheus-client
    - prompt-toolkit
    - protobuf
    - psutil
    - ptyprocess
    - pure-eval
    - pyasn1
    - pyasn1-modules
    - pygments
    - pyparsing
    - pyrsistent
    - python-dateutil
    - pytorch-pretrained-biggan
    - pytz
    - pywavelets
    - pyyaml
    - pyzmq
    - qtconsole
    - qtpy
    - requests-oauthlib
    - rsa
    - runipy
    - s3transfer
    - scikit-image
    - scikit-learn
    - scipy
    - send2trash
    - soupsieve
    - stack-data
    - tensorboard
    - terminado
    - threadpoolctl
    - tifffile
    - tinycss2
    - tornado
    - tqdm
    - traitlets
    - wcwidth
    - webencodings
    - werkzeug
    - widgetsnbextension
    - zipp

